### ISSUE TITLE
About Favorite Artist

### ISSUE THREAD

**Issue by kishimoto555555** [kishimoto555555/myCite#2]
People who click the artist can go to their Youtube Website.
- [x] collect the youtube channel links for the artists: ゆず,THE BAWDIES, Maroon5, Nissy
- [x] update the HTML file with anchor tag with a link to every related artist (open in new tab)
- [x] test the page locally

**Comment by kishimoto555555** [comment]
-[ ] a task of ゆず
-[ ] a task of THE BAWDIES
-[ ] a task of Maroon5
-[ ] a task of Nissy

**Comment by kishimoto555555** [comment]
- [ ] a task of ゆず
- [ ] a task of THE BAWDIES
- [ ] a task of Maroon5
- [ ] a task of Nissy

**Comment by kishimoto555555** [comment]
@oladhari 
Is it correct?

**Comment by oladhari** [comment]
I updated your issue description

**Comment by kishimoto555555** [comment]
Thank you so much.

**Comment by oladhari** [comment]
did you start a PR about this issue? if you start a PR please push it

**Comment by kishimoto555555** [comment]
I haven't yet.
I see. Thank you.
